#!/bin/bash

MEM=$(df -h | grep /dev/m | cut -b39-40)
SUFIX=$(df -h | grep /dev/m | cut -b41)
MEMCOMP=$(echo $MEM | cut -b1,3)

if [ $SUFIX == "G" ]
then 
	SUFIX=GiB
elif [ $SUFIX == "M" ]
then 
	SUFIX=MiB
elif [ $SUFIX == "k" ]
then
	SUFIX=kiB
fi


if [ $MEMCOMP -gt 30 -o $SUFIX != "MiB" -o $SUFIX != "kiB" ]
then
	echo "<span color='#2afc98'>   $MEM $SUFIX  </span>"
else
	echo "<span color='#fc5050'>   $MEM $SUFIX  </span>"
fi
