#!/bin/bash

MEM=$(free -h | grep Mem | cut -b28-30)
SUFIX=$(free -h | grep Mem | cut -b31)
MEMCOMP=$(echo $MEM | cut -b1,3)

if [ $SUFIX == "G" ]
then 
	SUFIX=GiB
elif [ $SUFIX == "M" ]
then 
	SUFIX=MiB
elif [ $SUFIX == "k" ]
then
	SUFIX=kiB
fi


if [ $MEMCOMP -lt 50 -o $SUFIX != "GiB" ]
then
	# dark theme
	# echo "<span color='#2afc98'>   $MEM $SUFIX  </span>"
	# light theme
	echo "<span color='#21773a'>   $MEM $SUFIX  </span>"
else
	# dark theme
	# echo "<span color='#fc5050'>   $MEM $SUFIX  </span>"
	# light theme
	echo "<span color='#772121'>   $MEM $SUFIX  </span>"
fi
