#!/bin/bash 

VOL=$(amixer get Master | grep -Eo '[0-9][0-9][0-9]?%')

VOLSHOW=$(echo $VOL | cut -b1-4)
VOLCOMP=$(echo $VOL | cut -b1-3)
if [ $VOLCOMP -ge 100 ]
then
	echo "<span color='#fc5050'> $VOLSHOW</span>"
	amixer set Master 100%
else
	VOLSHOW=$(echo $VOL | cut -b1-3)
	VOLCOMP=$(echo $VOL | cut -b1-2)
	if [ $VOLCOMP -gt 80 ]
	then
		echo "<span color='#fc5050'> $VOLSHOW</span>"
	elif [ $VOLCOMP -gt 60 -a $VOLCOMP -lt 80 ]
	then
		echo "<span color='#f7fc5d'> $VOLSHOW</span>"
	elif [ $VOLCOMP -gt 0 -a $VOLCOMP -lt 61 ]
	then
		echo " $VOLSHOW"
	else
		VOLSHOW=$(echo $VOL | cut -b1-2)
		VOLCOMP=$(echo $VOL | cut -b1)
		echo "<span color='#2afc98'>  $VOLSHOW </span>" 
	fi
fi
