#!/bin/bash


SIG=$(iwconfig wlp5s0b1 | grep -i quality | cut -b24-25)
POWER=$(iwconfig wlp5s0b1 | grep -i Power= | cut -b65-67)


if [ $POWER -n  "off" ]
then
	if [ $SIG -lt 20 ]
	then
		echo "<span color='#fc5050'> </span>"
	elif [ $SIG -gt 55 ]
	then
		echo "<span color='#2afc98'> </span>"
	else
		echo "<span color='#f5fc2a'> </span>"
	fi
fi
